name : Deploy to Replit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout репозитория
      uses : actions/checkout@v3

    - name : Отправить запрос на сервер Replit
      run: |
        curl -X POST https://
